### ISSUE TITLE
What to do after shell:startup

### ISSUE THREAD

**Issue by tapestoppa** [Discord-ian/fl-presence#1]
I'm lost after dragging and dropping the file in the drag and drop part and im wondering if the exe file of fl presence is supposed to do this
![image](https://user-images.githubusercontent.com/80783757/128648694-bae59997-e241-41d6-86d3-b39cb804914c.png)
![image](https://user-images.githubusercontent.com/80783757/128648711-85505a1a-25c5-4f23-b9c7-dc610392f08a.png)

**Comment by Discord-ian** [comment]
Definitely not intended. The script hasn't been touched in quite a while, I'll make it up to sync with the Ableton version and it should fix the issue you're having. Will add pull request shortly

**Comment by Discord-ian** [comment]
Should be mostly fixed in commit https://github.com/Discord-ian/fl-presence/commit/ff6d8d07da55d925563d5671c356c26430b08680

Download the new release from https://github.com/Discord-ian/fl-presence/releases/

Will close the issue after a response or in a couple days' time.
