### ISSUE TITLE
"Unhandled exception in script"

### ISSUE THREAD

**Issue by antonqwr** [Discord-ian/fl-presence#2]
When i open FL Studio, this error pop out.

![image](https://github.com/Discord-ian/fl-presence/assets/63048792/d7179a5c-1224-4c25-916a-b79f8218e8ca)

**Comment by Discord-ian** [comment]
Have you been able to use it successfully beforehand? 

Also, are you running the .exe file or directly from source?

**Comment by antonqwr** [comment]
Have you been able to use it successfully beforehand?

**Comment by antonqwr** [comment]
> Have you been able to use it successfully beforehand?

Yes, i get this everytime and i need to open it again from 'shell:startup'

> Also, are you running the .exe file or directly from source?

.exe file.

**Comment by Discord-ian** [comment]
The issue lied in a scenario where the RPC connection was lost and FL Presence wasn't handling the relevant errors. Should be fixed with commit 9b92ef16e43aab7eb86ab88dd02777a6f407acbc. You can download the new 1.9.1 binary [here](https://github.com/Discord-ian/fl-presence/releases/tag/1.9.1)
